### ISSUE TITLE
Rewrite in TypeScript

### ISSUE THREAD

**Issue by christofferaakre** [aephil/WeLD#18]
I think it would be a good idea to take the time to rewrite the code in Typescript for a few reasons:

* Easier to catch bugs
* We can use ES6 imports, etc. instead of having to stick a bunch of `.js` files in the `index.html`, this lets us get Intellisense, autocomplete, etc. from our code editors and helps to reason about the codebase

I don't think it should be that much effort, and if everyone agrees it's a good idea, I can do it.

**Comment by christofferaakre** [comment]
After having a closer look at it, it is actually a lot more work than I was expecting. There is just too much JS 'trickery' used in the code, like code that depends on other scripts having been run before it, objects being treated as booleans, etc. I don't think its really feasible anymore, so I'm going to close this issue.

**Comment by aephil** [comment]
FWIW that was also the conclusion I came to – a pity since as you say there are obvious advantages to TypeScript, but I think it will take us too far out of our way at this point.
