### ISSUE TITLE
Need to verify that the valence force is behaving correctly

### ISSUE THREAD

**Issue by christofferaakre** [aephil/WeLD#19]
We need to verify that the valence force implemented in `Physics.Forcemap.valenceAngle` is behaving correctly.

**Comment by christofferaakre** [comment]
@aephil @Paddy198 Any updates on this issue? Does the valence force seem to be behaving correctly?

**Comment by aephil** [comment]
@christofferaakre 

The first question is what this function is meant to do. It looks to me as if it is returning the force on the central atom; I assume that you are calculating the forces on the outer atoms elsewhere? (In your setup routine, do you need to list which atoms are involved with which potentials _but also in which roles_, i.e., as central or outer atom in an angle potential?)

Anyway, assuming this is right, I did some simple tests and this doesn't yet look as if it is working quite correctly:

    test = new ForceMap;
    d = {ri: {x:0, y:0, z:0}};
    data = [{ri: {x:1, y:0, z:0}}, {ri: {x:0, y:1, z:0}}];
    params = [1, Math.PI/2, 0, 1];
    // should be zero force since the angle is already 90º

    test.valenceAngle(d, data, params);
    // returns Object { x: -0, y: 0, z: -0 }
    // correct!

    d = {ri: {x:0.1, y:0.1, z:0}};
    // force should have components x = y < 0, z = 0 by symmetry, since the angle is greater than 90º
    test.valenceAngle(d, data, params);
    // returns Object { x: -0.21591652911979636, y: 0.21591652911979636, z: -0 }
    // looks suspect to me

    d = {ri: {x:0, y:0, z:0.1}};
    // force should have components x > 0, y > 0, z < 0 since the angle is less than 90º
    test.valenceAngle(d, data, params);
    // returns Object { x: 0.009900666556273618, y: -0.009900666556273618, z: -0 }
    // again this doesn't look correct

Have a go at debugging this (@Paddy198 please look at this too) and let me know if you need more of a hint as to what is going wrong.

Some related comments:
* You might want to consider adding a unit test framework to make this sort of thing easier; I'll add an issue with this suggestion.
* You might also want to document the units expected – here obviously the angle must be specified in radians, and you could think about the force constant units too.

**Comment by Paddy198** [comment]
Hi Chris, I've looked at the code, made some comments to help me get some bearings. Is it possible to see the `def` `valenceangle`  function?

**Comment by christofferaakre** [comment]
@Paddy198 I'm not sure what you mean "see the def `valenceangle`. If you are asking where it is defined, it is defined in `modules/physics/Forcemap.js`. the code was running as per my last commit (https://github.com/aephil/WeLD/tree/400af3ccdd280bb2b14c7d7356eec54f4dac66af)
I will check this again for you later today. Note that to run the code all you should need to do is open the 'index.html' file in your browser. I looked at your latest commit (https://github.com/aephil/WeLD/commit/268758596e51b9d59b92650c64b4995475dd7139).
It doesn't seem like this code is actually used anywhere. For that new script to have any effect on the codebase whatsoever, you would need to put a 'script' tag in 'index.html'. I will look through your commit in detail and try to answer your questions as best I can later today as well.

**Comment by aephil** [comment]
That commit is more or less just my test script from above, so it needs to be turned into a unit test not added to `index.html`.

**Comment by aephil** [comment]
@Paddy198 the equations in here come from https://hal-mines-paristech.archives-ouvertes.fr/hal-00924263/document. It would be a good idea to add that source as a comment.

**Comment by christofferaakre** [comment]
In addition to the issues noted by @aephil, another issue brought up during the project meeting is that we are only calculating the force on the central atoms. So the problem boils down to two parts:
1. Figure out what is wrong with the force calculation for the central atom
2. Calculate the forces for the other atoms involved in the interaction.

**Comment by christofferaakre** [comment]
There were two bugs present in the `valenceAngle` function:
1. To compute the vector `pa` as per https://hal-mines-paristech.archives-ouvertes.fr/hal-00924263/document, we need to compute `cb x (ba x bc)`, not `bc x (ba x bc)`. This has now been fixed by https://github.com/aephil/WeLD/commit/780ba732fdb2a60f2c178927ea76fccac42d4266
2. To compute the vector `ba`, we need to compute `a - b`, not `b - a`. This has been fixed by https://github.com/aephil/WeLD/commit/60d11a758afdc57ed770881ccb2b680d82ba2081

I will have a look at the other test case @aephil provided as well.

**Comment by christofferaakre** [comment]
Commit https://github.com/aephil/WeLD/commit/266d7db95636b7ea5e84f61542a42b8e181f017a adapts the second test case into a unit test, which now passes. So I believe the central atom force calculation is now working correctly, so all that remains is to calculate the forces for the other atoms involved in the interaction. Verification would be much appreciated
@aephil @Paddy198 @TakudzwaMakoni

**Comment by christofferaakre** [comment]
@aephil @TakudzwaMakoni @Paddy198 This issue should be fixed by this pull request now: https://github.com/aephil/WeLD/pull/23
Should we merge this to `master` and close this issue?

**Comment by TakudzwaMakoni** [comment]
Hi, walk me through the unit tests in `valenceAngle.test.js`, how do you run them? and what are they using for params and data in the function call valenceAngle on line 22 and 31. Im not familiar with the test suite so i don't know how these would run as is.

Also are you testing them on a lattice with more than two nodes? and valenceAngles initialised? because there arent any valence angles between only two nodes obviously.

**Comment by TakudzwaMakoni** [comment]
> In addition to the issues noted by @aephil, another issue brought up during the project meeting is that we are only calculating the force on the central atoms. So the problem boils down to two parts:
> 
> 1. Figure out what is wrong with the force calculation for the central atom
> 2. Calculate the forces for the other atoms involved in the interaction.

@aephil @christofferaakre Are we not already doing 2? since we iterate through each node every call of `velocityVerlet`, treating it as the central atom wrt its known neighbours. If we were to instead add the forces of A and C while on central atom B's step, when we get to A or C as the next central atom, would we not be erroneously applying the force again?

I think off the top of my head if we were to modify A and C in place while B is the central atom, we would need to introduce a cache of nodes already visited, i'm not sure whether it would save all much execution time in exchange for memory to be worth doing.

**Comment by christofferaakre** [comment]
> After some meditation, i think the method of modifying A and C on execution of B is right. The question becomes how does `velocityVerlet` catch the extra two forces, since by design it operates on one node at a time. It will need to be made to handle this case

I believe it already does so after my refactor? Now, instead of the forces just returning one force, they instead return an array of tuples, where each tuple contains the index of the node to act on, as well as the force to apply. Then in velocity verlet, i loop over all the "actions" (said tuples) and apply each force, so it should already handle this case unless I'm misunderstanding something.

**Comment by christofferaakre** [comment]
> Hi, walk me through the unit tests in `valenceAngle.test.js`, how do you run them? and what are they using for params and data in the function call valenceAngle on line 22 and 31. Im not familiar with the test suite so i don't know how these would run as is.
> 
> Also are you testing them on a lattice with more than two nodes, rather than what is currently in WeLD.js? else there shouldn't be any valence angles

The tests are ran using `jest`. Just run `npm test` from your console, and it will run all the tets. `data` and `params`
are defined on lines 5 and 8 respectively. And actually, the tests need to be refactored after the refactor since the expected
return values have changed, but the tests are being run on 3 nodes, note the call signature on `valenceAngle`: It takes the central node, as well as the index of the two other nodes. The unit tests are designed to only test small, easily testable chunks of code, such as these pure functions, so we don't initialise a lattice or anything. This is simply testing that with the right input, we get the expected output. There are some issues with how these unit tests are run because of how the codebase is set up, but for the most part it should hopefully be fine, just a little hacky. See this issue https://github.com/aephil/WeLD/issues/20
I was going to put some of this information in the readme yesterday, but I forgot, sorry about that.

**Comment by christofferaakre** [comment]
> I was going to put some of this information in the readme yesterday, but I forgot, sorry about that.

I added this information to the readme just now (https://github.com/aephil/WeLD/commit/7b22158ef14fedb28bead63a8914f73b8846c6e8)

**Comment by christofferaakre** [comment]
> > After some meditation, i think the method of modifying A and C on execution of B is right. The question becomes how does `velocityVerlet` catch the extra two forces, since by design it operates on one node at a time. It will need to be made to handle this case
> 
> I believe it already does so after my refactor? Now, instead of the forces just returning one force, they instead return an array of tuples, where each tuple contains the index of the node to act on, as well as the force to apply. Then in velocity verlet, i loop over all the "actions" (said tuples) and apply each force, so it should already handle this case unless I'm misunderstanding something.

@TakudzwaMakoni If you agree with me here, we can close this issue.

**Comment by TakudzwaMakoni** [comment]
> > > After some meditation, i think the method of modifying A and C on execution of B is right. The question becomes how does `velocityVerlet` catch the extra two forces, since by design it operates on one node at a time. It will need to be made to handle this case
> 
> > 
> 
> > I believe it already does so after my refactor? Now, instead of the forces just returning one force, they instead return an array of tuples, where each tuple contains the index of the node to act on, as well as the force to apply. Then in velocity verlet, i loop over all the "actions" (said tuples) and apply each force, so it should already handle this case unless I'm misunderstanding something.
> 
> 
> 
> @TakudzwaMakoni If you agree with me here, we can close this issue.

yes thats right i meant to update this after seeing your refactor, but it was quite late.

The issue can be closed. Have you seen my comment on the ValenceForce branch?

**Comment by christofferaakre** [comment]
> > > > After some meditation, i think the method of modifying A and C on execution of B is right. The question becomes how does `velocityVerlet` catch the extra two forces, since by design it operates on one node at a time. It will need to be made to handle this case
> > 
> > 
> > > 
> > 
> > 
> > > I believe it already does so after my refactor? Now, instead of the forces just returning one force, they instead return an array of tuples, where each tuple contains the index of the node to act on, as well as the force to apply. Then in velocity verlet, i loop over all the "actions" (said tuples) and apply each force, so it should already handle this case unless I'm misunderstanding something.
> > 
> > 
> > @TakudzwaMakoni If you agree with me here, we can close this issue.
> 
> yes thats right i meant to update this after seeing your refactor, but it was quite late.
> 
> The issue can be closed. Have you seen my comment on the ValenceForce branch?

Do you mean this https://github.com/aephil/WeLD/pull/23#issuecomment-968382132?
If so yeah, I'm not sure why there are two branches, but they are both gone now anyway after the merge.

**Comment by christofferaakre** [comment]
My bad sorry, I'm sure you were referring to the increasing restorative force (https://github.com/aephil/WeLD/pull/26#issuecomment-968398350)
Yeah, I saw that, I'll have a look at it today.

**Comment by christofferaakre** [comment]
I created an issue for the restorative spring force thing: https://github.com/aephil/WeLD/issues/28
This issue has been resolved, so I am closing it.
