### ISSUE TITLE
Add a unit testing framework

### ISSUE THREAD

**Issue by aephil** [aephil/WeLD#20]
Consider adding a framework such as Jest (https://jestjs.io/) to make unit testing easier. Then write unit tests for key bits of code.

**Comment by christofferaakre** [comment]
I merged the `testing` branch into `master` because there are new features on it that should be in `master`. In doing so I accidentally closed this issue, so I am reopening it.

**Comment by christofferaakre** [comment]
This issue should finally be closed by this pull request #35 once it gets merged in
