### ISSUE TITLE
Spring restorative force increasing over time

### ISSUE THREAD

**Issue by christofferaakre** [aephil/WeLD#28]
ive setup a scenario with two connected nodes, and i have contracted one by 0.5 units, as seen in `weld.js` line 134.
with this small initial contraction, the spring like action should be steady with the verlet algorithm. after a while the restorative force becomes larger, which is not expected. if you focus one of the nodes by clicking it, you can see the extension in the top corner of the sim canvas

_Originally posted by @TakudzwaMakoni in https://github.com/aephil/WeLD/issues/26#issuecomment-968398350_

**Comment by christofferaakre** [comment]
One weird thing I noticed straight away when trying to debug this is that the nodes seem to start with non-zero `vi`, when it should be zero according to the code in `modules/physics/Lattice.js`, right? Even if I do something like
```javascript
lattice.data.forEach(d => {
    d.vi.x = 0;
    d.vi.y = 0;
    d.vi.z = 0;
})
console.log(lattice.data);
``` 
right after your
```javascript
// TESTING: push the first node in the x direction to simulate an initial Extension
lattice.data[0].ri.x += 0.5;
```
I still see non-zero `vi` for both nodes. Any idea why this is the case?

**Comment by christofferaakre** [comment]
@TakudzwaMakoni any ideas?

**Comment by TakudzwaMakoni** [comment]
only thing which should modify vi after this is the verlet algorithm, i will try debugging this afternoon

**Comment by TakudzwaMakoni** [comment]
And yes, lattice.data is initialised with vi as zero vector, so this is strange.

**Comment by christofferaakre** [comment]
@TakudzwaMakoni It gets weirder: Try running this code right before you move the first node to the right by 0.5:
```javascript```
lattice.data.forEach(d => {                                              
+   5      d.vi.x = 0;                                                           
+   4      d.vi.y = 10;                                                          
+   3      d.vi.z = 10;                                                          
+   2   })                                                                       
+   1                                                                            
+ 140   console.log(lattice.data[0]);
```
When I try this, I get a random value for the x part, and a number just slightly less than 10 for the y and z parts when inspecting `vi`. Now, log out the actual `vi` instead of the entire node object:
```javascript
lattice.data.forEach(d => {                                              
+   5      d.vi.x = 0;                                                           
+   4      d.vi.y = 10;                                                          
+   3      d.vi.z = 10;                                                          
+   2   })                                                                       
+   1                                                                            
+ 140   console.log(lattice.data[0].vi);
```
With this,
![whole-object](https://user-images.githubusercontent.com/31142852/142198699-ee77dd08-a2d8-4ba6-8cb1-6a856901e61a.png)
![vi](https://user-images.githubusercontent.com/31142852/142198714-ecb53e6f-f055-423d-9704-d39f09634e2c.png)

 I get `{x: 0, y: 10, z: 10}` as expected every time!
I have no idea why these two would give a different result

**Comment by christofferaakre** [comment]
This thing with the velocities might be a separate issue, so i might a new issue for it: https://github.com/aephil/WeLD/issues/30

**Comment by TakudzwaMakoni** [comment]
in Verlet.js line 16, we are using f(t). but the equation demands f(t +dt), so we need to calculate not just the force aat current time t, but the force one timestep after. 

So we need to return the action at current t as well as the action at t + dt

**Comment by TakudzwaMakoni** [comment]
my pushes to master should fix this

**Comment by christofferaakre** [comment]
This does indeed seem to fix it. Great! I'll close this issue as well.
