### ISSUE TITLE
Initiated testing. Do you have any suggestions

### ISSUE THREAD

**Issue by Paddy198** [aephil/WeLD#29]
This could be a good first issue @Paddy198  to get a footing in the codebase if you want to have a go at it. Feel free to ask any questions here too if something is confusing.

_Originally posted by @christofferaakre in https://github.com/aephil/WeLD/issues/27#issuecomment-968741490_

I made some changes, like assigning different values to d. Please let me know if I can be of more use.

**Comment by christofferaakre** [comment]
You didn't push your changes, so I can't see the changes you made. Also, let's keep the discussion to the original issue 
(https://github.com/aephil/WeLD/issues/27) to keep more organised. When you push your changes, can you link your commit in the original issue?
