### ISSUE TITLE
Test Lennard-Jones potential

### ISSUE THREAD

**Issue by christofferaakre** [aephil/WeLD#31]
Implement a Lennard-Jones potential that repels particles at close range and attracts them at medium-to long range. See https://hal-mines-paristech.archives-ouvertes.fr/hal-00924263/document for details.

**Comment by christofferaakre** [comment]
This has been implemented as of commit https://github.com/aephil/WeLD/commit/1b077c1dc0fc06d45914f5e9d10cc0209556c4d6.
Tests are passing. Closing this issue.

**Comment by christofferaakre** [comment]
We should test if this potential actually works as intended. Shouldn't have closed this issue. Reopening.

**Comment by christofferaakre** [comment]
I have set up a simulation to test the implemented Lennard-Jones potential. See commit: https://github.com/aephil/WeLD/commit/190134d3d86caad64a795cdf733a0e5a472e9b06
For some reason, at distance > `r0`, the force is repulsive rather than attractive. I don't believe there is a missing minus sign anywhere. Any ideas what the problem is? @TakudzwaMakoni @Paddy198 @aephil

**Comment by Paddy198** [comment]
There seems to be an issue with the force at origin on the lj potential
![image](https://user-images.githubusercontent.com/92857298/143321157-5e743b59-c3c0-4ede-9299-9c2aac7bdec3.png)

**Comment by christofferaakre** [comment]
Can I see the code you wrote in the test file to get this result?
