### ISSUE TITLE
missing forces due to overwriting: restore calculation of total force

### ISSUE THREAD

**Issue by TakudzwaMakoni** [aephil/WeLD#32]
since the last refactor in Verlet.js, i notice the new implementation is not updating verlet using the net force but overwriting node.vf and node.rf for each action of each iteration of d. This approach will lead to incomplete force resolution, since this is not the aggregation or average of positions due to the forces. This becomes noticeable with large lattices, as you note that some nodes with many neighbours are interacting with some but not others.

The addition of extra actions which may contribute additional forces to other nodes than the current node in iteration adds more complexity, because this can be done retroactively i.e where a force on a node is applied after it has been iterated at d.forces.forEach, as well as to a node that will be operated on in future.

Some key points need to be addressed:

1. I think that the velocityverlet algorithm should strictly use net forces to update the positions to maintain simplicity of the modular implementation;  the vv timestep function should call only when all actions in the system have been resolved for each node.
2. therefore the net force for all nodes needs to be resolved separately from the vv algorithm. We cannot do this within the vv algorithm because this passes through all nodes only once, and means retroactive forces become wildly cumbersome to handle. 

I propose we implement another algorithm, which calculates the net force for each node,  to be run before the velocityverlet algorithm. The nodes should store then reset their own 'net force' vector each update call (resetting can be done inside of the updateState algorithm). This is not the same as the exising `forces`  stored inside a node, but is a single vector taking one value.

the process would be for one update call:
-----> resolve the net forces on each node by iterating all the actions; retroactive and proactive actions simply update the net force for the respective node, and no vv data (node.rf, node.vf) is modified at this stage.

-----> when all net forces are resolved, call the vv algorithm using the stored net forces 
*(the vv algorithm needs net force and net future force ; one timestep ahead. so we need to store actually two net forces.)

-----> updateState
allows all nodes to update to their newly resolved positions and velocities, all netForces are reset since they are to be recalculated in the next update call.

**Comment by christofferaakre** [comment]
This should fix this I believe. Tested with the `simulations/spring/testSpring.js` simulation. It also makes the beheaviour in the `testSpring2.js` seem like it could be correct, so I am pretty sure this fixes it properly.
